from dotenv import load_dotenv
load_dotenv()

import os

WEATHER_API_KEY = os.getenv('WEATHER_API_KEY')
GOOGLE_SEARCH_API_KEY = os.getenv('GOOGLE_SEARCH_API_KEY')
GOOGLE_SEARCH_CSE_KEY = os.getenv('GOOGLE_SEARCH_CSE_KEY')
PIXABAY_API_KEY = os.getenv('PIXABAY_API_KEY')
MYSQL_DATABASE_NAME = os.getenv('MYSQL_DATABASE_NAME')
MYSQL_SERVER_USER_NAME = os.getenv('MYSQL_SERVER_USER_NAME')
MYSQL_SERVER_USER_PASSWORD = os.getenv('MYSQL_SERVER_USER_PASSWORD')
MYSQL_SERVER_NAME = os.getenv('MYSQL_SERVER_NAME')
AZURE_STORAGE_CONNECTION_STRING = os.getenv('AZURE_STORAGE_CONNECTION_STRING')