# Generated by Django 3.1.2 on 2021-12-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=200)),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
