# Generated by Django 3.1.2 on 2021-12-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staricemountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createadd', models.DateTimeField()),
                ('updateadd', models.DateTimeField()),
                ('city', models.CharField(max_length=200)),
                ('maxtemperature', models.FloatField()),
                ('mintemperature', models.FloatField()),
            ],
        ),
    ]
